# Generated by Django 3.2.18 on 2023-08-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='Notification',
            new_name='notification',
        ),
    ]
